### ISSUE TITLE
Nachos and drink gibs create red boxes offset from world origin

### ISSUE THREAD

**Issue by e1m1j** [tech-nawar/sbox-cinema#22]
![image](https://github.com/tech-nawar/sbox-cinema/assets/86807353/5316ebf8-1cf5-465f-a736-73549c3dde21)

Happens when gibbing.

**Comment by Baik90** [comment]
cant compile w_popcorn_tub_01
![grafik](https://github.com/tech-nawar/sbox-cinema/assets/88790023/56a17922-1659-49fc-85f6-125d9f84fd49)
