### ISSUE TITLE
Q menu is used for both the inventory and the queue menu

### ISSUE THREAD

**Issue by e1m1j** [tech-nawar/sbox-cinema#35]
It's quite cumbersome to use either feature right now. Both windows open at the same time.

**Comment by Remscar** [comment]
What do you think the keybinds should be?

**Comment by chrisspieler** [comment]
I propose using Q for the weapon wheel as this is commonly used for weapon switching ("last weapon" in Half-Life 2, and "favorites menu" in Skyrim).

I propose using R (**reel**-oad) for the media player. It's easy to reach.

**Comment by Remscar** [comment]
That's reel cool

**Comment by chrisspieler** [comment]
I have implemented my proposed change, and it is working on the main branch.
