### ISSUE TITLE
CinemaGame.ValidateUser should be removed

### ISSUE THREAD

**Issue by chrisspieler** [tech-nawar/sbox-cinema#43]
This is just my opinion, but ValidateUser is bad for two reasons:

1. It requires us to hardcode a new Steam ID for every developer on the project (e.g. me, Stromic)
2. It gatekeeps some very useful test functionality that server admins and playtesters would want to use

I propose that we:
1. Remove ValidateUser and DevIDs from CinemaGame
2. For each method that previously had a ValidateUser guard clause, make its ConCmd a ConCmd.Admin.

If y'all concur, then I'll just go ahead and make the change myself.

**Comment by Remscar** [comment]
What if we just make it so anyone can use it for now? And later we add proper access control?
